# Generated by Django 3.1.2 on 2020-10-22 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_01', models.CharField(max_length=20)),
                ('field_02', models.CharField(max_length=20)),
                ('field_03', models.CharField(max_length=20)),
                ('field_04', models.CharField(max_length=20)),
                ('field_05', models.CharField(max_length=20)),
                ('field_06', models.CharField(max_length=20)),
                ('field_07', models.CharField(max_length=20)),
                ('field_08', models.CharField(max_length=20)),
                ('field_09', models.CharField(max_length=20)),
                ('field_10', models.CharField(max_length=20)),
                ('field_11', models.CharField(max_length=20)),
                ('field_12', models.CharField(max_length=20)),
                ('field_13', models.CharField(max_length=20)),
                ('field_14', models.CharField(max_length=20)),
                ('field_15', models.CharField(max_length=20)),
                ('field_16', models.CharField(max_length=20)),
                ('field_17', models.CharField(max_length=20)),
                ('field_18', models.CharField(max_length=20)),
                ('field_19', models.CharField(max_length=20)),
                ('field_20', models.CharField(max_length=20)),
            ],
        ),
    ]
